Sign Inページを作成する
ISDL-dev/ISDL-Sentinel pull request #143
Opened 2024-09-25 04:57 UTC by akiya125

## 目的/背景

- Sign Inページを作成する

# 前提条件

- #2 
が終了していること
 
## 変更内容（やること）

- FigmaのUIに従ったページを作成する
- headerにログイン情報を保持する
- useContextにログイン情報を保持する

## 関連 Issue

- #57

## 画面イメージ
login page
<img width="1624" alt="スクリーンショット 0006-09-25 13 41 58" src="https://github.com/user-attachments/assets/f2acfd34-adc9-4929-bccf-25a7e7998e5a">
<img width="1624" alt="スクリーンショット 0006-09-25 13 41 13" src="https://github.com/user-attachments/assets/87af131c-a720-4179-9345-cfedbb6bfb39">

2024-09-27 11:30 UTC, hoka-isdl requested changes
database/dataが差分として上がってきているので全て修正して
dev環境とprod環境ができたのでdev環境で開発している場合data_devが生成されるはず．
また，data_devが.gitignoreに記載されているのでgitには上がってこない．

2024-09-27 11:30 UTC, hoka-isdl commented on backend/Dockerfile
> +RUN go install github.com/cosmtrek/air@v1.44.0
これはmainが取り込まれていないように思える．
それとも意図があって変更したのかな？

2024-09-28 05:09 UTC, akiya125 commented on backend/Dockerfile
> +RUN go install github.com/cosmtrek/air@v1.44.0
自分の環境でdockerのbuildがエラー出るようになってので変更していました．
一旦元のコードに戻しておきます．

2024-09-28 05:30 UTC, akiya125 commented
database/dataの削除とdockerfileの修正をしました．

2024-09-29 05:22 UTC, kabigon-1015 commented on backend/Dockerfile
> +RUN go install github.com/cosmtrek/air@v1.44.0
@hoka-isdl
これ自分の環境でもmainの差分取り込んだ瞬間エラーおきたので、確認してみて欲しい

> OSSのIssue：https://github.com/air-verse/air/issues/605
> リリース履歴：https://github.com/air-verse/air/releases


上を参考に原因考えたが、dockerファイルで`@latest`つまり、常に最新versionを取得するようになっており、直近でリリースがあったのでそれが原因かと。
ただ最新verの差分を全て確認しても、明らかに動かなくなるような箇所は見つからなかったから、goのversionで互換性が取れなくて失敗してるのかも（最新verの差分でgoのversionを引き上げている箇所が何個かあった）

だから、goのversionを引き上げるか、air-verseのversionを1個前に戻す必要があると思う。
自分はこれでbuildできたし、ホットリロードも問題なく動作します
```dockerfile
RUN go install github.com/air-verse/air@v1.52.3
```

2024-09-29 15:47 UTC, hoka-isdl commented on backend/Dockerfile
> +RUN go install github.com/cosmtrek/air@v1.44.0
@kabigon-1015 
dockerでむやみにlatestとしないほうが良さそうだな．
imageを`FROM golang:1.23.1-alpine`にしてgoのversionを引き上げると上手く行ってる．
air-verseは1.23以上のversionでしか動かなくなってるな．現状1.20なので動かなくなったんだな．
なのでgoのversionを1.23.1（latest）にしてairは1.60.0（latest）にしておこうか．

2024-09-30 02:58 UTC, kabigon-1015 commented on backend/Dockerfile
> +RUN go install github.com/cosmtrek/air@v1.44.0
別PRでやります

2024-09-30 04:15 UTC, hoka-isdl reviewed
@kabigon-1015 
1点だけあるけどそのほかは問題ないのでmergeしてもいいかな
どう？

2024-09-30 04:15 UTC, hoka-isdl commented on frontend/src/routes/SignInDigest/index.tsx
> +      });
これはopenapiに定義できていないAPIか．
一旦これでOKだけど新たにopanapiに追加してこの部分を修正する感じにしようか．

2024-09-30 04:22 UTC, kabigon-1015 approved these changes

2024-09-30 04:23 UTC, kabigon-1015 commented
問題なさそう

2024-09-30 04:23 UTC, hoka-isdl approved these changes

2024-09-30 06:08 UTC, merged