入退室処理をできるようにする
ISDL-dev/ISDL-Sentinel pull request #39
Opened 2024-07-19 16:36 UTC by kabigon-1015

## 背景

- まずは基本のWeb上から入退室をできるようにしたい

## 変更内容（やること）

- 入退室ボタンを押したときにステータスを更新する

## 関連 Issue

- #6 

## 画面イメージ
特に画面上の実装はなし

## その他
ちょっと差分が多いので、わかりやすくするために細分化します
履歴テーブルとplace_idの更新は別のIssue立てたのでそっちでやります

2024-07-19 16:46 UTC, kabigon-1015 commented on frontend/src/routes/Home/index.tsx
> +
状態管理が入り次第変更

2024-07-19 16:46 UTC, kabigon-1015 commented on frontend/src/routes/Home/index.tsx
> +              </Button>
ここのコンポーネント特に意味がなかったので削除

2024-07-19 16:46 UTC, kabigon-1015 commented on backend/internal/model/status.go
> +)
ORMを使っていたらENUMで定義したものを取ってこれそうだが
今回使わないのでこの形（DBのinitを変更したらここも変更しないといけないからちょっと微妙）

2024-07-19 16:46 UTC, kabigon-1015 commented on backend/internal/services/status.go
> +	return schema.Status{UserId: status.UserId, Status: targetStatusName}, nil
次のIssueで履歴テーブルへのInsertとplace_idの変更を実装予定

2024-07-20 02:06 UTC, hoka-isdl requested changes
レビューしました！
コメントしたところを修正してくれればmergeしてOKです．

2024-07-20 02:33 UTC, kabigon-1015 commented on backend/internal/controllers/status.go
> +func PutStatusHandlerFunc(ctx *gin.Context) {
そこ悩ましいな
一応先作ってくれてたからそっちに合わすわ！

2024-07-20 02:35 UTC, hoka-isdl commented on backend/internal/controllers/status.go
> +func PutStatusHandlerFunc(ctx *gin.Context) {
俺もちょっと悩んだんよね〜
了解！`status_controller.go`のファイル名で今回はやってみようか

2024-07-20 02:37 UTC, kabigon-1015 commented
@hoka-isdl 
修正したので確認してほしい！

2024-07-20 02:42 UTC, hoka-isdl approved these changes
LGTM!

2024-07-20 02:42 UTC, merged