ランキングの画面デザインを実装する
ISDL-dev/ISDL-Sentinel pull request #77
Opened 2024-07-27 15:38 UTC by kabigon-1015

## 背景

- 入退室管理だけでは使うモチベーションが上がらないので、エンタメ要素を入れて少しでも使うモチベーションを上げたい
- ランキングの画面は他の画面と比較してデザインに少し力を入れるので、デザインの検討を含めこのIssueで対応したい

## 変更内容（やること）

- Figmaに基づき画面を構築するが、必要に応じてデザインを変更した
- デザイン重要な画面なのでしっかり目にレビューしてほしいです

## 関連 Issue

- #48 

## 画面イメージ

<img width="1464" alt="image" src="https://github.com/user-attachments/assets/7aff443a-3a3d-4899-9166-10312c381918">

2024-07-28 01:44 UTC, hoka-isdl requested changes
デザインめっちゃいいっすね．
ついでにモバイルのデザインもやってくれると嬉しいかな．
見たかんじTop3はモバイル対応してるけど4位からのListは対応していないようなのでそこだけ修正してくれればOKです．

2024-07-28 01:44 UTC, hoka-isdl commented on frontend/src/routes/Ranking/index.tsx
> +  Tr,
importしていないものはお掃除してもらえると助かる．

2024-07-28 01:44 UTC, hoka-isdl commented on frontend/src/features/RankingList/index.tsx
> +    user_name: `user${i}`,
ここはAPIを作るときに修正するってことか．

2024-07-28 05:01 UTC, kabigon-1015 commented
@hoka-isdl 
レビューあざます！
モバイルのデザインおいおいやろうかと思うので、完了したらまたメンションします

2024-07-28 05:02 UTC, kabigon-1015 commented on frontend/src/features/RankingList/index.tsx
> +    user_name: `user${i}`,
そういうことっす
上位10人まででいいかなとあとで増やすこともできる

2024-07-28 05:03 UTC, hoka-isdl commented
了解！モバイルのデザインはこのPRでする？

2024-07-28 05:21 UTC, kabigon-1015 commented
そうしようかな
先にデプロイ周りやるからそのあとで！

2024-07-29 17:31 UTC, kabigon-1015 commented
@hoka-isdl 
モバイル版完成しました〜
<img width="315" alt="image" src="https://github.com/user-attachments/assets/0d53cfe4-80b3-4acb-a005-a1bec6705334">

2024-07-29 17:37 UTC, kabigon-1015 commented on frontend/src/features/Footer/Footer.css
> +  width: 100vw;
％表記だと子コンポーネント次第でデザイン壊れるので、親は必ずvwもしくはvh表記で！

2024-07-29 17:37 UTC, kabigon-1015 commented on frontend/src/features/MobileNav/index.tsx
> +      width="100vw"
ここも

2024-07-29 17:40 UTC, kabigon-1015 commented on frontend/src/App.tsx
> +            overflowX={"hidden"}
ここも
scroll（横は特に）は基本なしで
収まらないならコンポーネントでscrollをつける

2024-07-30 00:44 UTC, hoka-isdl approved these changes
変更ありがとう！
mergeしてOK

2024-07-30 01:52 UTC, merged