LAの日程とメンバーを取得するAPIを実装する
ISDL-dev/ISDL-Sentinel pull request #94
Opened 2024-07-30 06:19 UTC by hoka-isdl

## 背景

- LAの日程とメンバーを取得するAPIを実装する

## 変更内容（やること）

- Api Schemaを変更
- LAの日程とメンバーを取得するAPIを作成

## 関連 Issue

- #87 

## 検証

![image](https://github.com/user-attachments/assets/4d9fa8b8-0183-4240-820d-c20399fda1b9)

2024-07-30 06:21 UTC, hoka-isdl commented on backend/internal/schema/model_get_lab_asistant_member_200_response_inner.go
>  }
memberを取得するときにcountも取得するようにした

2024-07-30 14:06 UTC, kabigon-1015 requested changes
1点だけお願い！

2024-07-30 14:06 UTC, kabigon-1015 commented on backend/internal/routers.go
> +		v1.GET("/lab-asistant/:date", controllers.GetLabAsistantScheduleController)
スキーマのパスパラメータが`month`になってるので統一お願い！

2024-07-30 14:06 UTC, kabigon-1015 commented on backend/internal/schema/model_get_lab_asistant_member_200_response_inner.go
>  }
あざます！

2024-07-31 01:03 UTC, hoka-isdl commented on backend/internal/routers.go
> +		v1.GET("/lab-asistant/:date", controllers.GetLabAsistantScheduleController)
修正した！

2024-07-31 02:12 UTC, kabigon-1015 approved these changes
LGTM！

2024-07-31 02:12 UTC, merged